version: '3.8'
services:
  frontend:
    container_name: vital-donation-web
    build:
      context: .
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:80"
    environment:
      - NGINX_BACKEND=${NGINX_BACKEND}